### ISSUE TITLE
Project version in CMake is outdated

### ISSUE THREAD

**Issue by philn** [Igalia/cog#115]
Currently hardcoded to 0.1.0. Should be 0.3.2 ? Would be nice to have an indication at runtime that we run a git snapshot or not, using `cog --version`.

**Comment by aperezdc** [comment]
We can check with CMake where `${CMAKE_SOURCE_DIR}/.git/` exists and run `git describe --tags` in that case to fill the value of `COG_VERSION_STRING`.
