### ISSUE TITLE
Youtube - "Your browser does not currently recognize any of the video formats available"

### ISSUE THREAD

**Issue by concreted** [Igalia/cog#125]
Hi, I'm trying to open Youtube links e.g. `cog -P fdo https://www.youtube.com/watch?v=-6_0XRRHAFU` but am getting this error on the Youtube page:

```
Your browser does not currently recognize any of the video formats available
```

I'm using WPE Webkit compiled from the 2.24.2 tarball, with these enabled features:
```
-- Enabled features:
--  ENABLE_ACCELERATED_2D_CANVAS ........... OFF
--  ENABLE_ENCRYPTED_MEDIA                   OFF
--  ENABLE_GTKDOC .......................... OFF
--  ENABLE_MEDIA_SOURCE                      ON
--  ENABLE_VIDEO ........................... ON
--  ENABLE_WEBDRIVER                         ON
--  ENABLE_WEB_AUDIO ....................... ON
--  ENABLE_WEB_CRYPTO                        ON
--  ENABLE_WPE_QT_API ...................... OFF
--  ENABLE_XSLT                              ON
--  USE_OPENJPEG ........................... ON
--  USE_WOFF2                                ON
```

Is there some other setting required to make Youtube playback work?

**Comment by philn** [comment]
`cog --enable-mediasource=1`

**Comment by philn** [comment]
You have MSE enabled at build-time, but by default it's disabled at runtime. This is a requirement for Youtube nowadays.

**Comment by concreted** [comment]
Will give this a try, thanks!

**Comment by concreted** [comment]
@philn Unfortunately I still get the same error when running `cog --enable-mediasource=1 -P fdo https://www.youtube.com/watch?v=-6_0XRRHAFU`. 

Also in the `cog --help-all` documentation it implies that these flags should be enabled by default:
```
BOOL values are either 'true', '1', 'false', or '0'. Ommitting the value implies '1'.
```

**Comment by philn** [comment]
> @philn Unfortunately I still get the same error when running `cog --enable-mediasource=1 -P fdo https://www.youtube.com/watch?v=-6_0XRRHAFU`.
> 

Can you please run cog with these env vars set? `GST_DEBUG="3,webkit*:6 GST_DEBUG_FILE=cog-gst.log` and then upload the cog-gst.log file here please.

> Also in the `cog --help-all` documentation it implies that these flags should be enabled by default:
> 
> ```
> BOOL values are either 'true', '1', 'false', or '0'. Ommitting the value implies '1'.
> ```

This is wrong. Omitting values imply `0`, AFAIK. This output needs to be fixed :)

**Comment by concreted** [comment]
I realized I didn't have Gstreamer installed, after installing the video does start to play back but is playing back way too fast. Looks like a lot of alsa-related errors in the log: https://gist.github.com/concreted/7ce4a52eef5eab20e5c3ee1cf75eeda7

**Comment by philn** [comment]
Yes, you need either a working ALSA setup or PulseAudio.

**Comment by concreted** [comment]
Youtube playback started working correctly once I got Pulseaudio properly configured for my device. Thanks!

**Comment by concreted** [comment]
FYI, I tried the command `cog -P fdo https://www.youtube.com/tv#/watch?v=bTqVqk7FSmY` and it still worked even without the `--enable-mediasource=1` flag.

**Comment by philn** [comment]
That's odd, but OK. :)

**Comment by philn** [comment]
Ah. MSE was enabled by default in https://bugs.webkit.org/show_bug.cgi?id=190243
