### ISSUE TITLE
Only first query parameter is used on loading URL

### ISSUE THREAD

**Issue by concreted** [Igalia/cog#131]
Using cog 0.3.1, I'm trying to load URLs that have more than one query param, but cog appears to only respect the first one. For example:
```
root@9c2262066c8c:/usr/src/app# cog -P fdo https://www.google.com?foo=bar&baz=qux
[1] 2623
root@9c2262066c8c:/usr/src/app# Cog-Message: 22:20:37.462: <https://www.google.com/?foo=bar> Load started.
Cog-Message: 22:20:37.850: <https://www.google.com/?foo=bar> Loading...
Cog-Message: 22:20:39.314: <https://www.google.com/?foo=bar> Loaded successfully.
```
The `Load started` message only references the first param `foo=bar`, where I would expect it to be `foo=bar&baz=qux`. 

I have built a custom web application that requires multiple URL params, and the application console log messages I see indicate that only the first one is being loaded.

**Comment by philn** [comment]
You need to quote the parameters, otherwise `&` is interpreted by the shell as putting the process in background.
`cog -P fdo "https://www.google.com?foo=bar&baz=qux"`

**Comment by concreted** [comment]
Ah of course! Thanks 👍
