### ISSUE TITLE
wpebackend-fdo required version for master should be updated in the README

### ISSUE THREAD

**Issue by MathieuDuponchelle** [Igalia/cog#133]
The README says that the minimum required version for master and cog-0.3 is 1.2.0, however with master it looks like the requirement is actually 1.3.1

**Comment by aperezdc** [comment]
The thing is that the version needed to build from the `master` branch may change as development progresses. I have pushed 21d21cc44a1fa52f7c897a7bd62b2a0bc6bfca29 which clarifies things a bit.

@MathieuDuponchelle Is the new wording in the README clear enough, or do you think it still needs some rewriting?

**Comment by MathieuDuponchelle** [comment]
fast response time! That's an improvement indeed, closing :)
