### ISSUE TITLE
backend failures when running cog-0.3 

### ISSUE THREAD

**Issue by MathieuDuponchelle** [Igalia/cog#134]
After building cog-0.3 with cmake and no options, I had the following issue when trying to run cog:

```
wpe: could not load the impl library. Is there any backend installed?: libWPEBackend-default.so: cannot open shared object file: No such file or directory
Aborted (core dumped)
```

After creating a symbolic `libWPEBackend-default.so -> libWPEBackend-fdo-1.0.so` link in /usr/lib64 , the problem is now different:

```
** (cog:30513): CRITICAL **: 17:33:41.583: WebKitWebViewBackend* webkit_web_view_backend_new(wpe_view_backend*, GDestroyNotify, gpointer): assertion 'backend' failed

** (cog:30513): ERROR **: 17:33:41.583: Could not instantiate any WPE backend.
```

Note: I couldn't find documentation listing information to provide when reporting a bug

**Comment by MathieuDuponchelle** [comment]
Ah, when passing `--platform=fdo` there's more information:

** (cog:30800): WARNING **: 17:42:04.097: Platform setup failed: Could not open Wayland display

I'm running x11 so that seems expected :) Is cog supposed to work with x11?

**Comment by philn** [comment]
The FDO platform plugin requires a valid Wayland session. Can you try in Weston?

**Comment by MathieuDuponchelle** [comment]
Yeah I've tried in weston but I've got a different set of problems I'm afraid. I've also installed cuda from the runfile installer and it installs some gl libs system wide, further muddying my problem. I'll close for now until I've been able to test on a cleaner setup, sorry for the noise :)
