### ISSUE TITLE
cog hangs after default priority change.

### ISSUE THREAD

**Issue by any1** [Igalia/cog#143]
The master branch of cog hangs on my system. I bisected the issue down to commit e39234ea4429944559316a6331886a7d668fe127: fdo: use the default priority for the wl_source.

**Comment by aperezdc** [comment]
@any1 You will need to use the `master` branches of libwpe, WPEBackend-fdo, and WPE WebKit as well. I am in the middle of releasing the first release candidate versions for the whole stack, so once they are out you can also try libwpe 1.3.91, WPEBackend-fdo 1.3.91, WPE WebKit 2.25.91, and Cog 0.3.91.

**Comment by any1** [comment]
Ahh, ok, I had the master of everything except WPE WebKit. Thanks!

**Comment by aperezdc** [comment]
@any1 Great, please give it a try. Please feel free to re-open this issue if you run into trouble again :ok_hand:
