### ISSUE TITLE
Error relocating /usr/lib/libsoup-2.4.so.1: g_file_info_get_modification_date_time: symbol not found

### ISSUE THREAD

**Issue by kytart** [Igalia/cog#151]
I compiled WPE Webkit and cog on Alpine Linux armv7 for Raspberry Pi. When I try to run `cog` I get an error

```
Error relocating /usr/lib/libsoup-2.4.so.1: g_file_info_get_modification_date_time: symbol not found
```

Not sure if this is a problem with cog or glib. I'll be happy for any guidance.

**Comment by philn** [comment]
That function was added in GLib 2.62. Which version do you have on the device?
Seems like your libsoup was compiled against GLib 2.62 but then an older version is picked up at runtime.
In any case, I'd say this is unrelated to Cog and I would advise to check your build environment and/or report a bug to whoever maintains Alpine Linux.

**Comment by kytart** [comment]
ok, my bad. I had glib 2.60 installed. Once I updated to 2.62, it's fine. Thanks!
