### ISSUE TITLE
Raspberry Pi: assertion 'backend' failed with wpebackend-rdk

### ISSUE THREAD

**Issue by kytart** [Igalia/cog#152]
I'm trying to run WPE Webkit on Raspberry Pi with wpebackend-rdk and I get errors that I don't know how to solve. I tried to look for answers first and couldn't find anything helpful. Maybe someone can help?

I get

```
** (cog:1789): CRITICAL **: 16:58:25.698: WebKitWebViewBackend* webkit_web_view_backend_new(wpe_view_backend*, GDestroyNotify, gpointer): assertion 'backend' failed

** (cog:1789): ERROR **: 16:58:25.698: Could not instantiate any WPE backend.
Trace/breakpoint trap
```

Thanks!

**Comment by kytart** [comment]
almost forgot, the command I'm running is
```
cog https://github.com
```

I also have wpewebkit-rdk installed and I have a symlink
```
/usr/lib/libWPEBackend-default.so /usr/lib/libWPEBackend-rdk.so
```

**Comment by aperezdc** [comment]
@kytart Could you please set the `G_MESSAGES_DEBUG=all` environment variable before running Cog and see if something relevant is shows?

Also, it would be useful to know which GPU your device has, and which build options you are passing to CMake when configuring the RDK backend.

**Comment by kytart** [comment]
@aperezdc I ran `G_MESSAGES_DEBUG=all cog https://github.com`and got
```
** (cog:1287): DEBUG: 13:44:40.111: platform_setup: Platform name: (null)
** (cog:1287): DEBUG: 13:44:40.111: Instantiating default WPE backend as fall-back.

** (cog:1287): CRITICAL **: 13:44:40.117: WebKitWebViewBackend* webkit_web_view_backend_new(wpe_view_backend*, GDestroyNotify, gpointer): assertion 'backend' failed

** (cog:1287): ERROR **: 13:44:40.117: Could not instantiate any WPE backend.
Trace/breakpoint trap
```

I'm using RPi 3B which has Broadcom VideoCore IV GPU.

> For the RaspberryPi you can use -DUSE_BACKEND_BCM_RPI=ON to make it use DispmanX directly

You mean, I should use this option when building WPE Webkit or cog? Because they both seem not to have this option in their cmake files and it doesn't have any effect. I'm building WPE Webkit 2.25.1.

Also I should mention, that I'm building it directly for my own RPi stack, not using Yocto or Buildroot.

**Comment by aperezdc** [comment]
> @aperezdc I ran `G_MESSAGES_DEBUG=all cog https://github.com`and got
> 
> ```
> ** (cog:1287): DEBUG: 13:44:40.111: platform_setup: Platform name: (null)
> ** (cog:1287): DEBUG: 13:44:40.111: Instantiating default WPE backend as fall-back.
> 
> ** (cog:1287): CRITICAL **: 13:44:40.117: WebKitWebViewBackend* webkit_web_view_backend_new(wpe_view_backend*, GDestroyNotify, gpointer): assertion 'backend' failed
> 
> ** (cog:1287): ERROR **: 13:44:40.117: Could not instantiate any WPE backend.
> Trace/breakpoint trap
> ```

Unfortunately, this does not add any new information :thinking: 

(Thanks for trying, though!)

> > For the RaspberryPi you can use -DUSE_BACKEND_BCM_RPI=ON to make it use DispmanX directly
> 
> You mean, I should use this option when building WPE Webkit or cog? Because they both seem not to have this option in their cmake files and it doesn't have any effect. I'm building WPE Webkit 2.25.1.

The `-DUSE_BACKEND_BCM_RPI=ON` option is for [WPEBackend-rdk](https://github.com/WebPlatformForEmbedded/WPEBackend-rdk). Sorry if I wasn't clear enough :innocent: 

You will also need to build and install the RaspberryPi [userland](https://github.com/raspberrypi/userland) libraries.

**Comment by kytart** [comment]
@aperezdc 

> The -DUSE_BACKEND_BCM_RPI=ON option is for WPEBackend-rdk. Sorry if I wasn't clear enough 😇

Right, makes more sense now, thanks :D 

So I tried to compile wpebackend-rdk with this flag and the build is failing. I created an issue here, so if u know how to fix that by any chance, please help! lol

Either way, I'll report here once get to the next step.

**Comment by kytart** [comment]
@aperezdc I finally managed to compile everything correctly and now cog finally runs but I get another error
```
[LibinputServer] Initialization of linux input system succeeded.
EGLDisplay Initialization failed: EGL_NOT_INITIALIZED
Cannot create EGL context: invalid display (last error: EGL_SUCCESS)
Cog-Message: 11:17:25.659: <https://github.com/> Load started.

(process:1909): libsoup-WARNING **: 11:17:26.325: soup-tld: There is no public-suffix data available.

(process:1909): libsoup-WARNING **: 11:17:26.326: soup-tld: There is no public-suffix data available.

(process:1909): libsoup-WARNING **: 11:17:26.326: soup-tld: There is no public-suffix data available.

(process:1909): libsoup-WARNING **: 11:17:26.327: soup-tld: There is no public-suffix data available.
Cog-Message: 11:17:26.446: <https://github.com/> Loading...
Cog-Message: 11:17:35.115: <https://github.com/> Loaded successfully.
```

**Comment by aperezdc** [comment]
@kytart I am not sure yet about the `EGL_NOT_INITIALIZED` issue. Regarding the libsoup warning, it is very likely caused by [libpsl](https://github.com/rockdaboot/libpsl/) installed incorrectly, and libsoup cannot find the data files supplied with libpsl. Please check that libpsl is being installed and configured with a correct `--prefix=` option.

**Comment by kytart** [comment]
@aperezdc I think libpsl is installed correctly

```
ls -l /usr/lib/libpsl*
lrwxrwxrwx    1 root     root            15 Oct  4 08:01 /usr/lib/libpsl.so -> libpsl.so.5.3.2
lrwxrwxrwx    1 root     root            15 Oct  4 08:01 /usr/lib/libpsl.so.5 -> libpsl.so.5.3.2
-rwxr-xr-x    1 root     root         13372 May 30 15:25 /usr/lib/libpsl.so.5.3.2
```

and then when I inspect, how it's linked in cog binary
```
ldd /usr/bin/cog | grep libpsl
	libpsl.so.5 => /usr/lib/libpsl.so.5 (0x73773000)
```

am I missing something?

**Comment by kytart** [comment]
I have a theory about why I'm gettingthe EGL issue, I described it [here](https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/629). Please take a look, maybe you'll know, what to do... Thanks!

**Comment by kytart** [comment]
When I opened this issue a while ago, I didn't know anything and since then I figured out I was going in a totally wrong direction. This issue isn't relevant anymore, so I'm closing it. Thanks for help!
