### ISSUE TITLE
Raspberry Pi: EGLDisplay Initialization failed: EDGL_NOT_INITIALIZED with wpebackend-fdo

### ISSUE THREAD

**Issue by kytart** [Igalia/cog#153]
I already asked a question about rdk backend [here](https://github.com/Igalia/cog/issues/152). I'm trying both backends and non of them work and I thought it's better to separate the questions since they issues are completely different from each other.

I'm trying to run WPE Webkit on Raspberry Pi 3 with wpewebkit-fdo backend and wayland. I installed VC4 drivers and added the overlay and everything.

I tried 2 variations of running weston

1. X11 - created xinitrc file with
```
weston --backend=x11-backend.so
```

2.  fbdev backend
```
weston --backend=fbdev-backend.so --tty=1 --device=/dev/fb0
```

Both approaches started weston and I could run some basic examples like `weston-flower`, etc. However if I try running cog
```
cog --platform=fdo https://github.com
```
I get
```
EGLDisplay Initialization failed: EGL_NOT_INITIALIZED
```

I tried searching and couldn't find out what that means. I'd be happy for any help. Thanks!

**Comment by philn** [comment]
I think you need the Weston DRM backend for -FDO to work.

**Comment by aperezdc** [comment]
@kytart I can confirm that you need to use `drm-backend.so` as pointed out by @philn — it is known to work with Mesa's `vc4` driver. Also, please use WPE WebKit 2.26.1 or newer: previous versions have a [bug which can result in a bogus EGL initialization error](https://bugs.webkit.org/show_bug.cgi?id=201505) when using recent versions of Mesa (alternatively, if you cannot update to 2.26.1, you can try applying the patch to your older WPE WebKit version before building).

**Comment by cchsu23** [comment]
I have the same issue with MT2712 and  weston is v.6.0.0. default is use drm-backend.so.
wpewebkit 2.32.1
libwpe 1.10.0
wpebackend-fdo 1.10.0
cog 0.10.0

$cog -P fdo https://www.youtube.com

**Comment by cchsu23** [comment]
[log is here](https://drive.google.com/file/d/1SA0CW0lh_l2NXzd9gVuxAEe5BYh-5hH8/view?usp=sharing)

**Comment by philn** [comment]
> I have the same issue with MT2712 and weston is v.6.0.0. default is use drm-backend.so.

Is weston's cairo nested client working?

**Comment by cchsu23** [comment]
No, I did not see this executable program.
Should I build weston with PACKAGECONFIG= egl cairo-glesv2  ??
And also build cairo with PACKAGECONFIG=glesv2      ??

**Comment by cchsu23** [comment]
I add 
PACKAGECONFIG_append_pn-weston = " cairo-glesv2"
PACKAGECONFIG_append_pn-cairo = " glesv2 egl"
PACKAGECONFIG_append_pn-wpewebkit = " 2dcanvas"
in local.conf

and I can execute weston-netsed, and it shows log as below, screen always be black
sh-3.2# weston-nested
could not load cursor 'dnd-move'
could not load cursor 'dnd-copy'
could not load cursor 'dnd-none'
Using local compositing with blits to render client surfaces
compositor: executing 'weston-nested-client' failed: No such file or directory
xkbcommon: ERROR: couldn't find a Compose file for locale "C.UTF-8"
could not create XKB compose table for locale 'C.UTF-8'.  Disabiling compose

**Comment by philn** [comment]
> and it shows log as below, screen always be black

You should see something on-screen. The `eglInitialize()` call in the client might fail silently. Can you check?

**Comment by cchsu23** [comment]
nothing on the screen. 

Cog is O.K.
(cog:4025): Cog-FDO- Initializing EGL...
(cog:4025): Cog-FDO- Creating Wayland surface...
(cog:4025): Cog-     platform_setup: Platform = 0xed203d30
(cog:4025): GLib     posix_spawn avoided (child_setup specified) 
(cog:4025): GLib-GIO Your application does not implement g_application_activate() and has no handlers connected to the 'activate' signal.  It should do one of these.
(cog:4025): Cog-FDO Enumerating seat capabilities:
(cog:4025): Cog-FDO   - Keyboard
(cog:4025): Cog-FDO   - Touch
(cog:4025): Cog-FDO Done enumerating seat capabilities.
(cog:4025): Cog-FDO Seat name: 'default'
(cog:4025): Cog-FDO Configuring new size: 1920x1080
(cog:4025): Cog-FDO New XDG toplevel configuration: (1920, 1080)
(cog:4025): Cog-FDO Resized EGL buffer to: (1920, 1080) @1x




Buit  Wpewebkit seems error here:

EGLDisplay Initialization failed: EGL_NOT_INITIALIZED

Cannot create EGL context: invalid display (last error: EGL_SUCCESS)

Cog-Core-[1;32mMessage[0m: [34m10:55:01.158[0m: <http://www.youtube.com/> Load started.

Cog-Core-[1;32mMessage[0m: [34m10:55:01.386[0m: <https://www.youtube.com/> Redirected.

Cog-Core-[1;32mMessage[0m: [34m10:55:01.817[0m: <https://www.youtube.com/> Loading...

Cog-Core-[1;32mMessage[0m: [34m10:55:12.608[0m: <https://www.youtube.com/> Loaded successfully.

**Comment by philn** [comment]
> > and it shows log as below, screen always be black
> 
> You should see something on-screen. The `eglInitialize()` call in the client might fail silently. Can you check?

This is the last time I ask. Is the cairo nested weston client displaying anything on screen? If not, then this is not a WPE issue, it's a bug in your driver.

**Comment by cchsu23** [comment]
Hi philn:
   You mean this is about userspace egl driver problem?  What's your egl driver use? from mesa or from arm?

**Comment by kytart** [comment]
@aperezdc it seems that this went over my head and I never replied since 2019. My apologies.

> @kytart I can confirm that you need to use `drm-backend.so` as pointed out by @philn — it is known to work with Mesa's `vc4` driver. Also, please use WPE WebKit 2.26.1 or newer: previous versions have a [bug which can result in a bogus EGL initialization error](https://bugs.webkit.org/show_bug.cgi?id=201505) when using recent versions of Mesa (alternatively, if you cannot update to 2.26.1, you can try applying the patch to your older WPE WebKit version before building).

Actually, also this is not possible on Raspberry Pi 3, only on RPi 4. RPi 3 doesn't support DRM but uses legacy Dispmanx API. At this point I'm not sure if running Weston on RPi 3 is even possible.

My original question was about RPi 3 which was the one I was working with at the time, but I didn't know any of this then. I know now. RPi 4 is working great with DRM backend.
