### ISSUE TITLE
Enabling logging breaks cogctl

### ISSUE THREAD

**Issue by TingPing** [Igalia/cog#157]
Works:

`env G_MESSAGES_DEBUG= cogctl open google.com`

Doesn't work:

`env G_MESSAGES_DEBUG=GLib-GIO cogctl open google.com` -> `open URL: No arguments expected`

(It is possible its a GLib issue but seems unlikely and I didn't debug further)

**Comment by aperezdc** [comment]
@TingPing: I cannot reproduce this anymore with current `master`. Was this with some branch of packaged release?

**Comment by TingPing** [comment]
This was a custom build. I can no longer reproduce on master either.

**Comment by aperezdc** [comment]
Okay, thanks for confirming @TingPing :ok_hand:
