### ISSUE TITLE
Horizontal scrolling not working

### ISSUE THREAD

**Issue by asabil** [Igalia/cog#158]
Hi,

Cog 0.4.0 (and also 0.3.0) don't seem to support horizontal scrolling as implemented on this test page: https://webkit.org/demos/scroll-snap/

Is there any special command line flags that should be enabled for horizontal scrolling to work?

Thanks,
Ali

**Comment by philn** [comment]
Even vertical scrolling doesn't work well here with Cog 0.4.0 running on WPEWebKit 2.26.1

**Comment by asabil** [comment]
Any pointers on where to look if we were to submit a patch to get this fixed?

**Comment by philn** [comment]
Maybe start in this function https://github.com/Igalia/cog/blob/master/platform/cog-platform-fdo.c#L576

**Comment by asabil** [comment]
Thank you! I started looking into this, and I realized that I was referring to "touch input" based scrolling whereas you are referring to "pointer input" based scrolling.

Do you think the two issues are the same/related?

Vertical scrolling using touch is working (although without any kinetic effects), whereas horizontal touch based scrolling doesn't work at all on the test page above.

**Comment by zdobersek** [comment]
Basis for this was necessary in libwpe and WebKit, and PR #182 should finally enable this functionality, finally, inside Cog. Feedback on that welcome. I'll close this issue once the PR lands.

**Comment by aperezdc** [comment]
I have landed #182 just a moment ago, so I think we can also close this :tada: 

Thanks @zdobersek!
