### ISSUE TITLE
fdo: properly support shm exports

### ISSUE THREAD

**Issue by zdobersek** [Igalia/cog#176]
We don't do that right now, leading to crashes when such a buffer is exported.

Occurrence of this problem reported in WPEBackend-fdo: https://github.com/Igalia/WPEBackend-fdo/issues/95

Intention: the pixel contents of the exported SHM buffer should effectively be copied into a new shm buffer and attached & committed to the wl_surface.

**Comment by zdobersek** [comment]
Also relevant: https://github.com/Igalia/meta-webkit/issues/138

**Comment by jameshilliard** [comment]
@zdobersek Is this something you plan to work on in the near future or was [this](https://github.com/Igalia/WPEBackend-fdo/pull/90) for a use case unrelated to cog?

**Comment by zdobersek** [comment]
@jameshilliard it was related to Cog.

I put together a prototype for the DRM platform plugin. The following branches are required:
- https://github.com/Igalia/WPEBackend-fdo/commits/zdobersek/shm-fixups
- https://github.com/Igalia/cog/commits/zdobersek/drm-shm-buffer-handling

You can run it via `WPEBACKEND_FDO_FORCE_SOFTWARE_RENDERING=1 cog -P drm <url>`. Feedback is welcome, for now I only tested it on an Intel laptop setup.

**Comment by jameshilliard** [comment]
@zdobersek Gave it a try but seems to not work for me(my setup has normally used the fdo platform eg `cog -P fdo` so not sure if I'm doing something wrong here with the drm platform).
```c
# WPEBACKEND_FDO_FORCE_SOFTWARE_RENDERING=1 cog -P drm http://neverssl.com
(cog:585): GLib-DEBUG: 20:51:51.347: posix_spawn avoided (fd close requested) 
** (cog:585): DEBUG: 20:51:51.357: platform_setup: Platform name: drm
** (cog:585): DEBUG: 20:51:51.357: platform_setup: Platform plugin: libcogplatform-drm.so
pci id for fd 10: 8086:0be2, driver (null)

** (cog:585): WARNING **: 20:51:51.922: Platform setup failed: Failed to initialize EGL
** (cog:585): DEBUG: 20:51:51.924: Instantiating default WPE backend as fall-back.

** (cog:585): CRITICAL **: 20:51:51.925: WebKitWebViewBackend* webkit_web_view_backend_new(wpe_view_backend*, GDestroyNotify, gpointer): assertion 'backend' failed

** (cog:585): ERROR **: 20:51:51.926: Could not instantiate any WPE backend.
Trace/breakpoint trap
```

**Comment by zdobersek** [comment]
Unclear why the DRM initialization fails for you. It could be that you don't have the DRM platform enabled in Mesa.

The changes in the `drm` platform plugin worked for me on an iMX.7 board. Integration in the `fdo` plugin should follow a similar pattern, just that the data should be copied into another shm buffer.

**Comment by jameshilliard** [comment]
> It could be that you don't have the DRM platform enabled in Mesa.

Yeah, so I'm building mesa with swrast/llvmpipe, that doesn't use DRM right?

**Comment by zdobersek** [comment]
swrast/llvmpipe acts as a driver, whereas DRM/KMS support is treated as a platform (along side other platforms like Wayland, X11 and surfaceless). I don't know whether building with swrast/llvmpipe as the only enabled driver disallows the building and usage of the DRM/KMS platform. It shouldn't since it's possible to present software-based framebuffers (i.e. dumb buffers) via DRM/KMS.

But for instance, if LIBGL_ALWAYS_SOFTWARE=1 is set in the environment, the DRM/KMS EGL platform fails to initialize -- I experienced that myself, and that's why the separate `WPEBACKEND_FDO_...` env was added. Perhaps this behavior is the same you're encountering with only the swrast/llvmpipe driver plugin enabled.

To update the instructions on how to run this on the DRM platform, `XDG_RUNTIME_DIR` also has to be set since the env is required to set up anonymous file objects that serve as the shared-memory backing:

`XDG_RUNTIME_DIR=/run/user/0 WPEBACKEND_FDO_FORCE_SOFTWARE_RENDERING=1 cog -P drm <url>`

And, again, the `LIBGL_ALWAYS_SOFTWARE` env must not be set.

**Comment by jameshilliard** [comment]
> To update the instructions on how to run this on the DRM platform, XDG_RUNTIME_DIR also has to be set since the env is required to set up anonymous file objects that serve as the shared-memory backing:

I was setting that already I think.

> And, again, the `LIBGL_ALWAYS_SOFTWARE` env must not be set.

I don't think I was setting that.

> Integration in the `fdo` plugin should follow a similar pattern, just that the data should be copied into another shm buffer.

If that should also be working soon I'll probably just wait for it as my build system(buildroot) doesn't seem to be properly set up for cog builds with `drm` plugin support anyways.

**Comment by jameshilliard** [comment]
I noticed [SHM-only mode](https://github.com/Igalia/WPEBackend-fdo/pull/111) got merged on the WPEBackend-fdo side, that's in preparation for adding fdo shm support to cog right?

**Comment by zdobersek** [comment]
Yes.

**Comment by jameshilliard** [comment]
@zdobersek Has there been any changes in regards to shm support in cog?

**Comment by aperezdc** [comment]
Support for SHM exports has been merged (https://github.com/Igalia/cog/pull/268) and I have used it recently myself while running Cog on Weston with its RDP backend. I'll close this issue; feel free to reopen it if there is something else missing in this regard 👌🏼
