### ISSUE TITLE
drm: properly support shm exports

### ISSUE THREAD

**Issue by zdobersek** [Igalia/cog#177]
Tangential to #176, but oriented towards the drm platform.

Relevant:
- https://github.com/Igalia/WPEBackend-fdo/issues/95
- https://github.com/Igalia/meta-webkit/issues/138

Intention: the pixel contents should be copied into a writable gbm_bo that's then imported into the DRM system and displayed as usual.

**Comment by zdobersek** [comment]
In prototype phase. The following branches are required:
- https://github.com/Igalia/WPEBackend-fdo/commits/zdobersek/shm-fixups
- https://github.com/Igalia/cog/commits/zdobersek/drm-shm-buffer-handling

To run it: `WPEBACKEND_FDO_FORCE_SOFTWARE_RENDERING=1 cog -P drm <url>`

The env is needed to completely avoid setting up the server-side parts of the wayland-egl platform, with only wl_shm protocol available for software-based rasterization. In the next release cycle we should see whether a dedicated SHM-oriented initialization entrypoint would be useful.

**Comment by WebReflection** [comment]
before I file another issue, my Raspberry Pi 4 doesn't want to know about `drm` ... black screen and that's it, while with fdo works more than great. Is this related or there's something else I'm not aware of? Thanks.

**Comment by jameshilliard** [comment]
@WebReflection This should be unrelated to the raspberry pi(I've tested that cog works on the Raspberry pi 3) as the Raspberry pi doesn't need shm exports from my understanding due to having a normal hardware accelerated mesa driver. The issue I'm running into where I need this is that I have a board(gma500 based) without hardware accelerated drivers and thus needs shm exports.

**Comment by WebReflection** [comment]
@jameshilliard thanks for clarifying. My *current* issue is with the Raspberry Pi **4**, launching `cog -P drm $PAGE` under Weston, but I haven't tried myself on the Pi 3, which I will do eventually.

I'll open another issue if 3 works but 4 doesn't than, as you said both have HW acceleration.

Thanks 👋

**Comment by jameshilliard** [comment]
@WebReflection I think you need to use the `fdo` option under weston, not `drm`.

**Comment by aperezdc** [comment]
This has been implemented in #268 a while ago, so I am going to close this issue.

@WebReflection @jameshilliard: Indeed when running under Weston one needs to use `fdo` (which should be called `wayland` in reality 🙃)
