### ISSUE TITLE
drm: Support manually specifying a mode to use

### ISSUE THREAD

**Issue by aperezdc** [Igalia/cog#198]
Currently the DRM platform plug-in chooses either the output's preferred mode, or if none reported the mode with the biggest area (in pixels). It would be desirable to allow manually specifying which resolution to use, which would override the automatic detection.

**Comment by zdobersek** [comment]
Could be done via the config file (#185)

**Comment by kvasdopil** [comment]
https://github.com/Igalia/cog/pull/208

**Comment by WebReflection** [comment]
@zdobersek 

> Could be done via the config file (#185)

do you mind explaining what exactly should be done to test a different resolution via drm?

lets say `1280x720` on cog -P drm website ... thanks!

**Comment by aperezdc** [comment]
> @zdobersek
> 
> > Could be done via the config file (#185)
> 
> do you mind explaining what exactly should be done to test a different resolution via drm?
> 
> lets say `1280x720` on cog -P drm website ... thanks!

Now that #208 has been merged, setting resolutions can be done with the `COG_PLATFORM_DRM_VIDEO_MODE` environment variable, for example:

```sh
export COG_PLATFORM_DRM_VIDEO_MODE=1280x720
cog --platform=drm https://wpewebkit.org
```

Let's close this issue, as setting video modes is now possible 😺
