### ISSUE TITLE
Loading a video file directly fails

### ISSUE THREAD

**Issue by clopez** [Igalia/cog#2]
When trying to use cog to load a raw video file fails.
Example

```
$ cog https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4
Cog-Message: <https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4> Load started.
Cog-Message: <https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4> Loading...

(cog:31588): Cog-WARNING **: <https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4> Page load error: Plug-in handled load
Cog-Message: <https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4> Loaded successfully.
Cog-Message: <https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4> Load started.
Cog-Message: <https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4> Loading...
Cog-Message: <https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4> Loaded successfully.
```

On the screen you first see the video for a brief moment (~1 second) and then an error page appears (Page load error: Plug-in handled load).

Needless to say that loading this (a video file directly) with other WebKit based launchers/browsers works fine.

**Comment by mcatanzaro** [comment]
> Needless to say that loading this (a video file directly) with other WebKit based launchers/browsers works fine.

I actually reported https://bugs.webkit.org/show_bug.cgi?id=183259 recently. Probably unrelated, though.

**Comment by clopez** [comment]
> I actually reported https://bugs.webkit.org/show_bug.cgi?id=183259 recently. Probably unrelated, though.

I think its something else maybe? as this works with any other launcher using the very same webkit, but not with cog.

Examples:

* You can test to build cog with webkitgtk+ support (to test easier on the desktop) with: ``` cmake -DCOG_USE_WEBKITGTK=ON ``` and then test cog vs webkitgtk+ minibrowser vs epiphany.
Loading the video directly works with epiphany and webkitgtk+ minibrowser, but not with cog.

* And the same if you build for WPE. Loading the video works on dyz, but not on cog.

**Comment by aperezdc** [comment]
Interestingly enough, a WebKitGTK+ build of Cog works fine for me, and a WPE build gets me a different warning, notice the `Frame load interrupted` below:

```
Wayland: Got a wl_compositor interface
Wayland: Got a wl_seat interface
Wayland: Got an xdg_shell interface
Wayland: Got a wl_shell interface
EGL initialized with version 1.4

(cog:14875): GLib-GObject-WARNING **: 22:09:51.636: gsignal.c:2523: signal 'web-process-crashed' is invalid for instance '0x559d997898d0' of type 'WebKitWebView'
Seat caps: Pointer Keyboard
Seat name 'default'
New XDG toplevel configuration: (0, 0)
Cog-Message: 22:09:51.693: <https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4> Load started.
New XDG toplevel configuration: (0, 0)

(cog:14875): Cog-WARNING **: 22:09:52.807: <https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4> Page load error: Frame load interrupted
Cog-Message: 22:09:52.808: <> Loaded successfully.
Cog-Message: 22:09:52.808: <https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4> Load started.
Cog-Message: 22:09:52.808: <https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4> Loading...
Cog-Message: 22:09:52.828: <https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4> Loaded successfully.
New XDG toplevel configuration: (0, 0)
```

@clopez: BTW, your log output has `Plug-in handled load`, which is kind of suspicious. Were you running a Cog WebKitGTK+ build with the Flash plug-in installed? (Or some other plug-in which can play videos.)

**Comment by clopez** [comment]
This happens also on a board with WPE recently built with meta-webkit. So its not related to NPAPI plugins as:
1. WPE doesn't support that (AFAIK)
2. I have no installed any NPAPI plugins on the image.

Example 
```
root@wandboard:~# G_MESSAGES_DEBUG=all cog https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4
(cog:1810): Cog-DEBUG: platform_setup: Platform name: (null)
(cog:1810): Cog-DEBUG: Instantiating default WPE backend as fall-back.
xkbcommon: ERROR: couldn't find a Compose file for locale "C"
Cog-Message: <https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4> Load started.
Cog-Message: <https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4> Loading...
[INFO]	bitstreamMode 1, chromaInterleave 0, mapType 0, tiled2LinearEnable 0

(cog:1810): Cog-WARNING **: <https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4> Page load error: Plug-in handled load
Cog-Message: <https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4> Loaded successfully.
Cog-Message: <https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4> Load started.
Cog-Message: <https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4> Loading...
Cog-Message: <https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4> Loaded successfully.
```

**Comment by aperezdc** [comment]
@clopez: True, there is no support for NPAPI plug-ins in WPE, yet. 

According to [this WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=48561) the `Plug-in handled load` is returned when loading the resource has been passed to some plugin *or* media engine. It seems that in this case we still get notified of a load “error”, but we need to ignore it and let WebKit handle that anyway (see [this in the Epiphany code](https://git.gnome.org/browse/epiphany/tree/embed/ephy-web-view.c?id=4c037c90f055d76a92889a72280b5196367b5f04#n2530)).

Conclusion: the load-error handling in Cog needs some extra juice, I'll try to come up with a patch.

**Comment by aperezdc** [comment]
I have figured out why I was getting `Frame load interrupted`: the local build of WPE that I have been using for testing this had video support disabled at build time. Let's rebuilt WPE with video support enabled to test this properly before submitting the PR!

**Comment by concreted** [comment]
I'm actually experiencing what seems like the same issue using cog 0.3.1 and WPE Webkit 2.24.2, compiled with `ENABLE_VIDEO=ON`. I get this error in console when running `COG_PLATFORM_FDO_VIEW_FULLSCREEN=1 cog -P fdo https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4`:

```
(cog:4804): Cog-WARNING **: 02:04:02.763: <https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4> Page load error: Frame load interrupted
```

The cog window shows the same text.

Any ideas on what could cause this still? 0.3.1 has this fix from what I can tell. These are the enabled features for my WPE build:
```
-- Enabled features:
--  ENABLE_ACCELERATED_2D_CANVAS ........... OFF
--  ENABLE_ENCRYPTED_MEDIA                   OFF
--  ENABLE_GTKDOC .......................... OFF
--  ENABLE_MEDIA_SOURCE                      ON
--  ENABLE_VIDEO ........................... ON
--  ENABLE_WEBDRIVER                         ON
--  ENABLE_WEB_AUDIO ....................... ON
--  ENABLE_WEB_CRYPTO                        ON
--  ENABLE_WPE_QT_API ...................... OFF
--  ENABLE_XSLT                              ON
--  USE_OPENJPEG ........................... ON
--  USE_WOFF2                                ON
```

**Comment by clopez** [comment]
> Any ideas on what could cause this still? 0.3.1 has this fix from what I can tell. These are the enabled features for my WPE build:

I can't reproduce with cog+webkitgtk. Didn't tried with cog+wpe as I don't have a build at hand, not sure if some one else can check.

Are you able to reproduce the video with gstreamer? (to discard a decoder problem)
This should play the video
```
gst-play-1.0 https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4
```
Otherwise you are missing the h264 decoders on your build or something like that

**Comment by concreted** [comment]
Thanks, will try with gstreamer and report back.

**Comment by concreted** [comment]
@clopez Running `gst-play-1.0` fails with the following logs:
```
root@24d9a15197e4:/usr/src/app# gst-play-1.0 https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4
Press 'k' to see a list of keyboard shortcuts.
Now playing https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4
Prerolling...
Redistribute latency...
WARNING Could not get/set settings from/on resource.
WARNING debug information: gstalsasink.c(502): set_hwparams (): /GstPlayBin:playbin/GstPlaySink:playsink/GstBin:abin/GstAlsaSink:alsasink0:
Unable to set buffer time 200000 for playback: Invalid argument
ERROR Could not get/set settings from/on resource. for https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4
ERROR debug information: gstalsasink.c(617): set_hwparams (): /GstPlayBin:playbin/GstPlaySink:playsink/GstBin:abin/GstAlsaSink:alsasink0:
Unable to set hw params for playback: Invalid argument
Reached end of play list.
```

This seems related to audio? I do have pulseaudio installed and `aplay -l` lists valid playback devices. Will see if I can play a test audio file.
