### ISSUE TITLE
fdo: Using Alt+Left or Alt+Right to go back/forward results in error

### ISSUE THREAD

**Issue by aperezdc** [Igalia/cog#20]
Using `Alt+Left`:

```
** (cog:10901): CRITICAL **: 15:21:39.085: void webkit_web_view_go_back(WebKitWebView*): assertion 'WEBKIT_IS_WEB_VIEW(webView)' failed
```

Conversely, with `Alt+Right`:

```
** (cog:10901): CRITICAL **: 15:21:39.745: void webkit_web_view_go_forward(WebKitWebView*): assertion 'WEBKIT_IS_WEB_VIEW(webView)' failed
```

**Comment by elima** [comment]
This is coming from old code, when that code had access to the WebKitWebView object. Nowadays that object is kept by cog.c, and the platform-fdo's reference is null; hence the error.

IMO, the correct way to fix this is to define a key-binding interface in cog's launcher and move these calls there.

**Comment by aperezdc** [comment]
@elima Indeed, having some way of allowing Cog to request key bindings from a platform plug-in would be the best.

In the meantime, if we want to fix the hardcoded keybindings provided by the FDO platform plug-in, a stopgap measure could to obtain the Web view with:

```c
WebKitWebView *web_view = cog_launcher_get_web_view (cog_launcher_get_default ())
```

This will work fine due to `CogLauncher` being a singleton. I'll have a patch for this in a bit.
