### ISSUE TITLE
drm platform - rotate posibility

### ISSUE THREAD

**Issue by dusan-ivanco** [Igalia/cog#205]
Hi, is it possible to add rotate option for DRM platform? Yes, i known, that i may rotate display in config.txt (dtparam=rotate=90), but then touch is not working properly (dtparam=swapxy=0 doesn't help). Thank you.

**Comment by aperezdc** [comment]
This has been implemented in https://github.com/Igalia/cog/pull/371 and the needed options are [documented here](https://igalia.github.io/cog/platform-drm.html#configuration-file-options). Something like this should make the output have a 90º rotation:

```sh
cog -P drm -O renderer=gles,rotation=1 http://wpewebkit.org
```

@dusan-ivanco I hope the above works for you. Feel free to reopen the issue if you find something else missing.
