### ISSUE TITLE
Failure to initialize EGL - wl_drm@13: error 0: authenicate failed

### ISSUE THREAD

**Issue by dswalla** [Igalia/cog#212]
I am trying to launch the latest cog build from the meta-webkit Yocto layer (https://github.com/Igalia/meta-webkit) under the Sway compositor but running into some issues. 

I am running:
```
EGL_LOG_LEVEL=debug G_MESSAGES_DEBUG=all WAYLAND_DISPLAY=/run/user/1200/wayland-0 cog -P fdo http://localhost:3000
```

The error message I get is:
```
(cog:1283678): Cog-FDO-DEBUG: 14:15:59.781: Using 'wl_output' interface obtained from the Wayland registry.
(cog:1283678): Cog-FDO-DEBUG: 14:15:59.781: Initializing EGL...
libEGL debug: Native platform type: wayland (autodetected)
wl_drm@13: error 0: authenicate failed
libEGL debug: EGL user error 0x3001 (EGL_NOT_INITIALIZED) in eglInitialize


(cog:1283678): GLib-CRITICAL **: 14:15:59.781: g_source_destroy: assertion 'source != NULL' failed

** (cog:1283678): WARNING **: 14:15:59.781: Platform setup failed: Could not initialize  EGL (0x3001)
** (cog:1283678): DEBUG: 14:15:59.782: Instantiating default WPE backend as fall-back.

** (cog:1283678): CRITICAL **: 14:15:59.782: WebKitWebViewBackend* webkit_web_view_backend_new(wpe_view_backend*, GDestroyNotify, gpointer): assertion 'backend' failed

** (cog:1283678): ERROR **: 14:15:59.782: Could not instantiate any WPE backend.
```

Any help or insight would be appreciated, thanks!

**Comment by zdobersek** [comment]
Can you provide the output when running with `WAYLAND_DEBUG=1`? That should give a better insight on what Sway is providing for us to work with.

Separately but related -- what kind of hardware and software (i.e. the graphics stack) are you using?

**Comment by dswalla** [comment]
[cog.log](https://github.com/Igalia/cog/files/4887558/cog.log)
I've attached the output from running with `WAYLAND_DEBUG=1`

This is on machine with an x86 processor and Mesa graphics drivers.

**Comment by timemaster5** [comment]
Do you have any clue on how to sort this out? I am experiencing the same problem on Raspberry Pi 3b+, 32 bit, FDO backend.

**Comment by dj-curls** [comment]
I am having the same issue as @timemaster5 using buildroot. 

I'm not 100% sure the VC4 drivers are being loaded, but the main error I get is:

`libEGL warning: MESA-LOADER: failed to open swrast (search paths /usr/lib/dri)`
`libEGL warning: MESA-LOADER: failed to open swrast (search paths /usr/lib/dri)`


`(cog:337): GLib-CRITICAL **: 16:06:14.647: g_source_destroy: assertion 'source != NULL' failed`
`** (cog:337): WARNING **: 16:06:14.648: Platform setup failed: Could not initialize  EGL (0x3001)`
`** (cog:337): CRITICAL **: 16:06:14.648: WebKitWebViewBackend* webkit_web_view_backend_new(wpe_view_backend*, GDestroyNotify, gpointer): assertion 'backend' failed`
`** (cog:337): ERROR **: 16:06:14.649: Could not instantiate any WPE backend.`

**Comment by timemaster5** [comment]
I couldn't track this problem down, and there is a huge chance that it has already been fixed in later versions of Weston/Cog/WPE, really don't know what component could cause that, sorry for that.

For me, I was able to resolve this by upgrading Cog to the latest version of 0.7.1 from 0.6.x, Weston from 7 to 8 and wpewebkit from 2.28.1 to 2.28.4.

I hope that helps.

**Comment by dj-curls** [comment]
No worries, thanks for the info. 

For reference, I'm using the (as of now) latest Buildroot LTS version 2020.02.4 

Unfortunately my understanding is the Buildroot version specifies package versions, and is a pain to update individual packages. 

Nonetheless I think it's a good avenue to explore, thank you .

**Comment by dj-curls** [comment]
For future reference, my issue was that buildroot wasn't rebuilding mesa properly after selecting different drivers to be included. 

Selected drivers were left out of /usr/lib/dri

A simple `make clean` then rebuilding made sure all the selected drivers were built, and has allowed me to move past this error on to the next error (Segmentation Fault)

**Comment by aperezdc** [comment]
> For future reference, my issue was that buildroot wasn't rebuilding mesa properly after selecting different drivers to be included.
> 
> Selected drivers were left out of /usr/lib/dri
> 
> A simple `make clean` then rebuilding made sure all the selected drivers were built, and has allowed me to move past this error on to the next error (Segmentation Fault)

Given this comment, let's close the issue, as it was not a Cog issue after all. If this comes up again we can reopen it later 😺
