### ISSUE TITLE
wl: Support more than the first input event source

### ISSUE THREAD

**Issue by aperezdc** [Igalia/cog#214]
Currently the <del>FDO</del> Wayland platform module only picks input events from the first event sources (keyboard, touch, pointer, etc.) advertised by the compositor. Ideally we would support multiple sources.

**Comment by psaavedra** [comment]
https://github.com/Igalia/cog/pull/217 provides support for multiple seats.

**Comment by aperezdc** [comment]
Closing, the PR with multiple seat support has been merged a while ago into the `master` branch.
