### ISSUE TITLE
dir-handler no longer works with wpewebkit 2.28

### ISSUE THREAD

**Issue by asabil** [Igalia/cog#216]
When running cog with --dir-handler=file:///... the following critical errors are printed and the page never loads:

```
** (cog:9510): CRITICAL **: 09:32:56.254: void webkit_web_context_register_uri_scheme(WebKitWebContext*, const char*, WebKitURISchemeRequestCallback, gpointer, GDestroyNotify): assertion 'g_ascii_strcasecmp(scheme, "file") != 0' failed

** (cog:9510): CRITICAL **: 09:32:56.256: void webkit_web_context_register_uri_scheme(WebKitWebContext*, const char*, WebKitURISchemeRequestCallback, gpointer, GDestroyNotify): assertion 'g_ascii_strcasecmp(scheme, "file") != 0' failed
```

This is due to the following change in webkit/wpewebkit: https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/e2f02d8fc585ce03d79f5c6fa50139aeaf4dd66a#diff-1998d17e73c9819a556b028c87b78f4b

This change was later reverted/relaxed in webkit in:
https://github.com/WebKit/webkit/commit/877ffa2b8ecb7f40c8b36e83fff9ec0222fbda63#diff-1998d17e73c9819a556b028c87b78f4b

**Comment by philn** [comment]
CC @aperezdc

**Comment by philn** [comment]
I suppose this will no longer happen in 2.30 then... Can you try the latest 2.29 development release? It's always welcome to get feedback from users before a stable release...

**Comment by asabil** [comment]
The issue is that cog registers a uri handler for the `file` scheme which is not supported. The latest webkit version will still print out a warning.

**Comment by philn** [comment]
Oh, right!

**Comment by aperezdc** [comment]
You don't want to use `file` with `--dir-handler=` anyway because WebKit has built-in support for `file://` URIs. The idea is to use `--dir-handler=` to register a *custom* scheme, for example the following makes the files from the `/opt/webapp` directory available with the `app://` scheme:

```sh
cog --dir-handler=app:/opt/webapp app://
```

**Comment by asabil** [comment]
Ah ok, thank you!
