### ISSUE TITLE
i.MX6QDL video render issue

### ISSUE THREAD

**Issue by otavio** [Igalia/cog#231]
The video rendering seems it is skipping the padding bytes:

![2020-10-16_09-03](https://user-images.githubusercontent.com/25278/96256344-dba92480-0f8e-11eb-8baa-13be20dba057.png)

This was reproduced using:

i.MX6Q SABRE SD board, using Etnaviv GPU driver, Linux 5.4.70 and mesa 20.0.2. This was done using Dunfell branch from Yocto Project.

**Comment by aperezdc** [comment]
Hello @otavio, I have a couple of questions

- Which platform plug-in are you using: DRM, FDO, or nothing? Or, in other words, which `--platform=` value are you using to run Cog?
- Which versions of Cog, WPE WebKit, libwpe, and WPEBackend-fdo are you using?

**Comment by otavio** [comment]
It is using FDO and we're using Cog 0.8 and WPE 2.30.

**Comment by philn** [comment]
No issue with `gst-play-1.0 --videosink glimagesink <url>` ?

**Comment by aperezdc** [comment]
> It is using FDO and we're using Cog 0.8 and WPE 2.30.

Thanks for the quick reply.

Two more questions:

- Which compositor are you using? Weston?
- I suppose the expectation is that the image (or is it a video) of Woody Woodpecker covers the whole screen area, right?
- If this is a video, has it been fullscreened?
- Is the Cog Wayland surface fullscreened (with the `COG_PLATFORM_FDO_VIEW_FULLSCREEN` environment variable) or maximized (with `COG_PLATFORM_FDO_VIEW_MAXIMIZE`)?

**Comment by otavio** [comment]
It is using `COG_PLATFORM_FDO_VIEW_FULLSCREEN`.

**Comment by otavio** [comment]
> No issue with `gst-play-1.0 --videosink glimagesink <url>` ?

No, but we can run it here with a specific URL if desired for checking.

**Comment by philn** [comment]
The same asset plays fine in gst-play then?

Can you provide a pipeline dump? See
https://github.com/Igalia/meta-webkit/wiki/Providing-useful-GStreamer-Zero-copy-issue-reports

**Comment by fbertux** [comment]
Hi @philn 

The logs are attached here. Please, if you need more information let me know.

[logs.tar.gz](https://github.com/Igalia/cog/files/5392380/logs.tar.gz)

**Comment by philn** [comment]
Try to download this video with youtube-dl, pick the VP9 version and try to play it with gst-play-1.0 as I commented before. Compare the pipelines too, specifically the video decoder being used and downstream converters.

**Comment by otavio** [comment]
@philn we're not supposed to be using VP9 as we disabled it, also i.MX6 takes up to VP8 as far as I can tell. Am I wrong? @dv1

**Comment by philn** [comment]
Why do I see an `avdec_vp9` decoder in your pipeline then? :)

**Comment by otavio** [comment]
It was caused by the vp9; we fixed the ffmpeg setting to offer the supported codecs and it worked fine :-)
