### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Igalia/cog#248]
I would like to point out that an identifier like “[`_CogRequestHandlerInterface`](https://github.com/Igalia/cog/blob/f421c0a1dc43cd472b21499c4514067d2563a24a/core/cog-request-handler.h#L24 "Update candidate")” [does not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by aperezdc** [comment]
I am afraid that there is not much we can do about this because the `G_DECLARE_INTERFACE()` GLib macro expects this name to be used. In practice doing this is harmless so I do not see much of a point in trying to fix this—and at any rate we would it fixed in GLib.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
