### ISSUE TITLE
Fullscreen support

### ISSUE THREAD

**Issue by philn** [Igalia/cog#25]
It would be nice to have a command-line option for this. And also one to be able to specify the default window size.

**Comment by philn** [comment]
There's an env var, already, I think that's a good start :)
Would be nice though to have runtime keyboard shortcuts so we can easily toggle between fullscreen states.

**Comment by philn** [comment]
Default window size also has env vars, good for me!

**Comment by elima** [comment]
@philn, F11 should toggle fullscreen. It is currently hardcoded in -fdo.

**Comment by philn** [comment]
Sweet, so... what's left for this issue? Not much it seems :)

**Comment by aperezdc** [comment]
Well, it would be better that the feature is not tied to the FDO platform only; which would need solving #22, I'd say.

**Comment by concreted** [comment]
I couldn't find any documentation for these env vars, the ones defined here seem to be the ones used for fullscreen: https://github.com/Igalia/cog/blob/6f1be78103323bc9e0964b73372e017b6c1b1cb5/platform/cog-platform-fdo.c

For example `COG_PLATFORM_FDO_VIEW_FULLSCREEN=1 cog -P fdo https://threejs.org/examples/#webgl_terrain_dynamic` worked for me, using weston with the default desktop shell. 

Hope that helps anyone who is looking for how to run this fullscreen

**Comment by davidperrenoud** [comment]
Today's equivalent would be `COG_PLATFORM_WL_VIEW_FULLSCREEN=1 cog -P wl https://threejs.org/examples/#webgl_terrain_dynamic`

**Comment by manuelafm** [comment]
Documentation for Wayland platform in: https://github.com/Igalia/cog/blob/master/docs/platform-wl.md

**Comment by aperezdc** [comment]
I will close this tentatively, as we have ways for:

- Setting default window size.
- Setting fullscreen.
- Toggling fullscreen with `F11`.

While not all plug-ins support those, we can use new issues to tackle that, like #22 mentioned earlier.
