### ISSUE TITLE
Question: Rendering to existing OpenGL Context

### ISSUE THREAD

**Issue by nemosupremo** [Igalia/cog#254]
This is more of a question - I'm poking around libcog and it looks like the way the fdo/wayland backend works is essentially we call `wpe_view_backend_exportable_fdo_egl_create` with a function pointer that gives us a `wpe_fdo_egl_exported_image`. Assuming I don't need any inputs, could I simply use this library to render to *any* compatible OpenGL context - as in embed webkit into an already existing opengl application?

**Comment by philn** [comment]
There is a "Discussions" feature enabled for this project now. Next time please start a thread there!

**Comment by philn** [comment]
By making your app depend on wpebackend-fdo you can indeed use its API to render exported EGLImages using a shared context, AFAIK. That's what we did for GstWPE and QtWPE, for instance.

**Comment by philn** [comment]
> There is a "Discussions" feature enabled for this project now. Next time please start a thread there!

https://github.com/Igalia/cog/discussions

**Comment by nemosupremo** [comment]
Thank you - I didn’t even know about gstwpe, which should be easier to integrate with
