### ISSUE TITLE
Rename “fdo” platform plug-in to “wayland”

### ISSUE THREAD

**Issue by aperezdc** [Igalia/cog#335]
The so-called “fdo” platform plug-in should be called Wayland. It uses FDO technologies? Sure! But so do the X11 and GTK4 ones, and it can be argued that the name is very confusing because in the end what it does is making Cog a Wayland client application that needs a compositor running.

Opinions?

**Comment by aperezdc** [comment]
If we do not like the long name, we can call it `wl` instead of `wayland`, I would be fine with that.

**Comment by Cwiiis** [comment]
This was fixed by https://github.com/Igalia/cog/pull/351
