### ISSUE TITLE
Video doesn't play on cog

### ISSUE THREAD

**Issue by GobGeeklord** [Igalia/cog#364]
Hi there,

I'm using cog version 0.7.1 (WPE WebKit 2.28.1) on my imx6 system and i can't play video on it.
If i use gst-play directly the video plays very well, but when calling it on cog it doesn't:

> root@bbk:~# GST_DEBUG=1 cog --platform=fdo --enable-write-console-messages-to-stdout=1 https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4
> Cog-Message: 10:48:01.097: <https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4> Load started.
> Cog-Message: 10:48:01.956: <https://people.igalia.com/clopez/wkbug/video/big_buck_bunny.mp4> Loading...
> 
> ====== AIUR: 4.4.5 build on Sep 29 2021 21:07:52. ======
>         Core: MPEG4PARSER_06.16.01  build on Dec 11 2018 03:04:05
>  file: /usr/lib/imx-mm/parser/lib_mp4_parser_arm11_elinux.so.3.2
> ------------------------
>     Track 00 [audio_0] Enabled
>         Duration: 0:01:00.138333000
>         Language: eng
>     Mime:
>         audio/mpeg, mpegversion=(int)4, channels=(int)2, rate=(int)22050, bitrate=(int)64000, stream-format=(string)raw, codec_data=(buffer)1390
> ------------------------
> 
> ====== BEEP: 4.4.5 build on Sep 29 2021 21:07:53. ======
>         Core: AAC decoder Wrapper  build on Dec  7 2017 18:13:49
>  file: /usr/lib/imx-mm/audio-codec/wrap/lib_aacd_wrap_arm12_elinux.so.3
> CODEC: BLN_MAD-MMCODECS_AACD_ARM_03.09.00_CORTEX-A8  build on Sep 20 2017 15:02:14.
> ------------------------
>     Track 01 [video_0] Enabled
>         Duration: 0:01:00.095000000
>         Language: eng
>     Mime:
>         video/x-h264, parsed=(boolean)true, alignment=(string)au, stream-format=(string)avc, width=(int)640, height=(int)360, framerate=(fraction)24/1, codec_data=(buffer)0142e01eff0100152742e01ea9181405ff2e00d418041adb0ad7bdf01001000428de09c8
> ------------------------
>     Track 02 [subtitle]: Disabled
>         Codec: 0, SubCodec: 0
> ------------------------
>     Track 03 [subtitle]: Disabled
>         Codec: 0, SubCodec: 0
> ------------------------
> [INFO]  bitstreamMode 1, chromaInterleave 0, mapType 0, tiled2LinearEnable 0

and then the screen stays black forever. The video controls shows up and i can see the video time counting.

if i play it via gst-play: 

> root@bbk:~# gst-play-1.0 big_buck_bunny_720p_1mb.mp4
> Press 'k' to see a list of keyboard shortcuts.
> Now playing /home/root/big_buck_bunny_720p_1mb.mp4
> Prerolling...
> ====== AIUR: 4.4.5 build on Sep 29 2021 21:07:52. ======
>         Core: MPEG4PARSER_06.16.01  build on Dec 11 2018 03:04:05
>  file: /usr/lib/imx-mm/parser/lib_mp4_parser_arm11_elinux.so.3.2
> ------------------------
>     Track 00 [video_0] Enabled
>         Duration: 0:00:05.280000000
>         Language: und
>     Mime:
>         video/x-h264, parsed=(boolean)true, alignment=(string)au, stream-format=(string)avc, width=(int)1280, height=(int)720, framerate=(fraction)25/1, codec_data=(buffer)014d401fffe10017674d401fda014016ec0440000003004000000c83c60ca801000468ef3c80
> ------------------------
> ------------------------
>     Track 01 [audio_0] Enabled
>         Duration: 0:00:05.312000000
>         Language: und
>     Mime:
>         audio/mpeg, mpegversion=(int)4, channels=(int)6, rate=(int)48000, bitrate=(int)384829, stream-format=(string)raw, codec_data=(buffer)11b0
> ------------------------
> 
> ====== BEEP: 4.4.5 build on Sep 29 2021 21:07:53. ======
>         Core: AAC decoder Wrapper  build on Dec  7 2017 18:13:49
>  file: /usr/lib/imx-mm/audio-codec/wrap/lib_aacd_wrap_arm12_elinux.so.3
> CODEC: BLN_MAD-MMCODECS_AACD_ARM_03.09.00_CORTEX-A8  build on Sep 20 2017 15:02:14.
> display(/dev/fb0) resolution is (1280x720).
> ====== OVERLAYSINK: 4.4.5 build on Sep 29 2021 21:07:55. ======
> display(/dev/fb0) resolution is (1280x720).
> [INFO]  bitstreamMode 1, chromaInterleave 0, mapType 0, tiled2LinearEnable 0
> display(/dev/fb0) resolution is (1280x720).
> Redistribute latency...
> 0:00:05.3 / 0:00:05.3
> Reached end of play list.
> Total showed frames (133), display master blited (133), playing for (0:00:05.320000000), fps (25.000).

Does enyone ever got this issue?

Regards

**Comment by philn** [comment]
What sink is used by gst-play?

**Comment by GobGeeklord** [comment]
HI @philn,

I'm not sure, but looking for the logs it looks like overlaysink?

**Comment by philn** [comment]
Is that NXP specific? I suppose the issue here is that the WebKit GL sink is incompatible with whatever format those NXP decoders is outputting.

**Comment by GobGeeklord** [comment]
We solved this question going to mainline on 5.x + YP dunfell.
