### ISSUE TITLE
CI: Cross-build images for ARM do not detect wayland-scanner

### ISSUE THREAD

**Issue by aperezdc** [Igalia/cog#374]
For example this can be seen in this [build log](https://github.com/Igalia/cog/runs/4140268316), apparently `wayland-scanner` exists but then some check fails:

```
-- Checking for module 'wayland-scanner'
-- Could NOT find WaylandScanner (missing: WAYLAND_SCANNER WAYLAND_SCANNER_VERSION WAYLAND_SCANNER_CODE_ARG) 
-- Checking for module 'wayland-protocols'
--   Found wayland-protocols, version 1.21
CMake Error at /home/runner/toolchain/sysroots/x86_64-pokysdk-linux/usr/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find WaylandProtocols (missing: WAYLAND_SCANNER)
Call Stack (most recent call first):
  /home/runner/toolchain/sysroots/x86_64-pokysdk-linux/usr/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindWaylandProtocols.cmake:202 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  platform/wayland/CMakeLists.txt:16 (find_package)
```

I wonder if this might be related to the wildcard I added in c8756bd074fdc936a722052e4775424aaecb32a0 😇

**Comment by psaavedra** [comment]
it could useful to verify the wayland-scanner binary is provided or not by the toolkit. If not I should fix that.

**Comment by aperezdc** [comment]
> it could useful to verify the wayland-scanner binary is provided or not by the toolkit. If not I should fix that.

It turns out that `wayland-scanner` is in the toolchain, both the ARM and x86_64 versions:

```
% fd -tx -F wayland-scanner ~/tc -X file -b '{}'       
ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, BuildID[sha1]=d2eef2931c8a381c1f14961848273aab75905ff2, for GNU/Linux 3.2.0, stripped
ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /home/aperez/tc/sysroots/x86_64-pokysdk-linux/lib/ld-linux-x86-64.so.2, BuildID[sha1]=0a9310ae460a197b3343f7eac674d77a52b13477, for GNU/Linux 3.2.0, stripped
%
```

I wonder if there might be some other reason why with the latest toolchain versions the check is failing. I wonder if the `FindWaylandScanner.cmake` file might be doing something wrongly, or whether the environment setup script included with the toolchain might be adding the ARM version to the path and CMake finds it but then it cannot execute it 🤔

**Comment by psaavedra** [comment]
that could be a reason. the binary in the path should be the one for x86
for build time.
