### ISSUE TITLE
drm on imx6

### ISSUE THREAD

**Issue by woutervanh** [Igalia/cog#403]
I'm having some issue getting drm to work on imx6 (linux 5.14 / etnaviv). 
Cog 0.12.0 (WPE WebKit 2.34.5)

> Cog-INFO: 17:42:12.791: com.igalia.Cog.Platform:
> Cog-INFO: 17:42:12.791:   drm - 200/CogDrmPlatform
> (cog:787): Cog-DEBUG: 17:42:12.845: platform_setup: Platform name: (null)
> (cog:787): Cog-DRM-DEBUG: 17:42:12.874: init_config: overriding device_scale value, using 1.00 from shell
> (cog:787): Cog-DRM-DEBUG: 17:42:12.884: init_drm: enumerated device 0x1dfea18, available_nodes 1
> (cog:787): Cog-DRM-DEBUG: 17:42:12.884: init_drm:   DRM_NODE_PRIMARY: /dev/dri/card1
> (cog:787): Cog-DRM-DEBUG: 17:42:12.884: init_drm: enumerated device 0x1dfec88, available_nodes 5
> (cog:787): Cog-DRM-DEBUG: 17:42:12.884: init_drm:   DRM_NODE_PRIMARY: /dev/dri/card0
> (cog:787): Cog-DRM-DEBUG: 17:42:12.884: init_drm:   DRM_NODE_RENDER: /dev/dri/renderD128
> (cog:787): Cog-DRM-DEBUG: 17:42:12.885: init_drm: using device 0x1dfea18, DRM_NODE_PRIMARY /dev/dri/card1
> (cog:787): Cog-DRM-DEBUG: 17:42:12.885: init_drm: 1 connectors available
> (cog:787): Cog-DRM-DEBUG: 17:42:12.885: init_drm:  connector id 66, type 7, connected, 1 usable modes
> (cog:787): Cog-DRM-DEBUG: 17:42:12.886: init_drm:    [0]: '1280x800', 1280x800@60, flags 4, type 72 (preferred)
> (cog:787): Cog-DRM-DEBUG: 17:42:12.886: init_drm: using connector id 66, type 7
> (cog:787): Cog-DRM-DEBUG: 17:42:12.886: init_drm: using mode [0] '1280x800'
> Failed to create /home/root/.cache for shader cache (Read-only file system)---disabling.
> (cog:787): Cog-DEBUG: 17:42:13.087: platform_setup: Selected CogDrmPlatform @ 0x1de1b30
> 
> (cog:787): GLib-GIO-WARNING **: 17:42:13.116: Your application does not implement g_application_activate() and has no handlers connected to the 'activate' signal.  It should do one of these.
> Failed to create /home/root/.cache for shader cache (Read-only file system)---disabling.
> Cannot obtain EGL WPE context configuration: EGL_SUCCESS
> Cannot obtain EGL WPE context configuration: EGL_SUCCESS

Then it loads the page and ends with load successfull. However, the screen is still showing the terminal...
What can be the issue here? Am I missing something? Kmscube runs fine

**Comment by aperezdc** [comment]
@woutervanh Could you try setting the environment variables `XDG_RUNTIME_DIR` and `XDG_CACHE_DIR` pointing to some writable location like `/tmp`? For example like this:

```sh
XDG_CACHE_DIR=/tmp \
XDG_RUNTIME_DIR=/tmp \
G_MESSAGES_DEBUG=Cog,Cog-Core,Cog-DRM \
    cog -P drm http://ddg.gg
```

**Comment by aperezdc** [comment]
@woutervanh Have you managed to get things working on your end?

I am relatively sure Cog + DRM should work on i.MX6 devices, and as a matter of fact the latest [stable release 0.18.2](https://github.com/Igalia/cog/releases/tag/0.18.2) includes a fix for them.

**Comment by woutervanh** [comment]
Referring to https://github.com/Igalia/cog/issues/144 (not solved yet though)
