### ISSUE TITLE
wrong taballs listed in cog 0.12.3 release

### ISSUE THREAD

**Issue by sen-h** [Igalia/cog#418]
the release tab for version 0.12.3 has tarballs for 0.12.2 listed
![2022-03-28-125656_2556x1401_scrot](https://user-images.githubusercontent.com/76416488/160458887-564992f8-c32f-43de-94a1-79d29e1d3322.png)

**Comment by aperezdc** [comment]
@sen-h Fixed, thanks for the heads up!
