### ISSUE TITLE
There are some problems when I build the cog0.5.1(wpewebkit-2.32.0) on ubuntu20.04TLS

### ISSUE THREAD

**Issue by Geroge-W** [Igalia/cog#482]
Hi， 
there are some problemes when I am trying to build the cog0.5.1(wpewebkit-2.32.0) on the ubuntu20.04TLS. the sys and the cog packets version are as follows: 
             system: ubuntu20.04TLS
             cog packets: cog-0.5.1.tar.xz*
                                  libwpe-1.10.0.tar.xz*
                                  wpebackend-fdo-1.6.0.tar.xz*
                                  wpewebkit-2.32.0.tar.xz*
and I use the command step are as follows:

     /* build libwpe-1.10.0 */
      cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=Yes -DCMAKE_BUILD_TYPE=Debug - 
      DCMAKE_INSTALL_PREFIX=/home/mi/wpe/inst

     make -j8 install

     /* env variable */
    export PATH=$PATH:/home/wpe/inst/bin

    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/wpe/inst/lib

    export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/home/mi/wpe/inst/lib/pkgconfig

     /* build wpebackend-fdo-1.6.0 */
     cmake .. -DCMAKE_INSTALL_PREFIX=/home/wpe/inst

     make -j8 install
 
     /* build wpewebkit */
     ./Tools/wpe/install-dependencies

      cmake .. -DCMAKE_BUILD_TYPE=Debug -DPORT=WPE -DENABLE_MINIBROWSER=ON -DCMAKE_CXX_FLAGS="-fpermissive" -DCMAKE_INSTALL_PREFIX=/home/wpe/inst -DWPE_INCLUDE_DIR=/home/wpe/inst/include/wpe-1.0 -GNinja

      ninja install

     /* build cog */
     cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/wpe/inst -GNinja
     ninja install

    /* open a weston window */
    weston --socket=wpe

    /* open the weston terminal */
      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/wpe/inst/lib
      cog --platform=fdo https://www.baidu.com

libwpe, wpebackend-fdo, wpewebkit and cog building was succeed, but when I  cog --platform=fdo https://www.baidu.com, the ERROR occurs，as follows:
         ** (WPEWebProcess:102174): WARNING **: Error loading the injected bundle (/home/wpe/inst/lib/wpe-webkit-1.0/injected-bundle/libWPEInjectedBundle.so): undefined symbol: WTFReportAssertionFailure
Segmentation fault (core dumped)

above of all, whould you like to give me some advices？ thanks very much，looking forward to your replay！

**Comment by philn** [comment]
Is there a good reason for using such old versions?

**Comment by aperezdc** [comment]
For the record, the current stable releases (libwpe 1.12.3, wpebackend-fdo 1.12.1, wpewebkit 2.36.7, cog 0.14.0) support Ubuntu 20.04, as per our [dependencies policy](https://trac.webkit.org/wiki/WebKitGTK/DependenciesPolicy).

**Comment by aperezdc** [comment]
@Geroge-W: Also, I would recommend using `-DCMAKE_BUILD_TYPE=RelWithDebInfo` if your goal is to have a build that you can load in GDB to debug and obtain stack traces. In particular using `-DCMAKE_BUILD_TYPE=Debug` with WPE WebKit will result in a _slow_ build with debugging assertions built (some of which will make WebKit crash unexpectedly!). Using `Debug` which are expected to be used only by WebKit developers themselves.

**Comment by Geroge-W** [comment]
@philn @aperezdc Thanks for your prompt reply, I have tried the releases（libwpe 1.8.0, wpebackend-fdo 1.9.90, wpewebkit 2.32.0, cog 0.10.1）and it was worked well on Ubuntu 20.04, thanks again for your suggestions, and I will study cog it further.
