### ISSUE TITLE
Unable to exit cog while running on DRM

### ISSUE THREAD

**Issue by philn** [Igalia/cog#495]
### Discussed in https://github.com/Igalia/cog/discussions/493

<div type='discussions-op-text'>

<sup>Originally posted by **chrisvollorenew** September 20, 2022</sup>
Hello, 

I am running cog on drm (cog -P drm file:/// ..  ) mode on an embedded device.
The cog browser launches from a process that is called at boot.
If I plug in a keyboard to my embedded device, I am able to navigate the browser, but I am not sure how to force the browser to exit.
Ctrl + C does not seem to be working.
How can I force cog to exit with the keyboard?</div>

**Comment by chrisvollorenew** [comment]
@philn thank you! Looking forward to hearing the solution.

**Comment by aperezdc** [comment]
Currently we do not have support for key bindings in the DRM plug-in, it needs to be implemented.

**Comment by aperezdc** [comment]
With https://github.com/Igalia/cog/pull/574 now all platfoprm plug-ins have support for the basic key bindings. Using `Ctrl-W` should close Cog also when running on DRM/KMS (the rest of the available key bindings are [listed in the documentation](https://igalia.github.io/cog/method.View.set_use_key_bindings.html#description)).
