### ISSUE TITLE
Using va VaVp8dec for hw video acceleration on Intel

### ISSUE THREAD

**Issue by gustavqmatic** [Igalia/cog#525]
We are trying to use the new va plugin in gstreamer to play video using va-api. The old legacy plugin enabled with WEBKIT_GST_ENABLE_LEGACY_VAAPI works so I think drivers etc is correct (but it is deprecated and should not be used as we understands it).

We have enabled the va plugin using this line
export GST_PLUGIN_FEATURE_RANK=vah264dec:MAX,vah265dec:MAX,vampeg2dec:MAX,vavp8dec:MAX,vavp9dec:MAX

The attached screen shoot show a webpage with a background vp8 video that is wrong. The video is playing, the colors is somewhat correct but everything is scrambled. We see the same issue with h264 video.

To debug the issue I added env GST_DEBUG_DUMP_DOT_DIR to get a picture of the pipeline. I have attached png version of the graph. I don’t know exactly what should happen but to me it looks strange that in sink GstGLUploadElement the format change from NV12 to RGBA (and that the texture-target is exernal-oes and not 2D).

Looking in https://bugs.webkit.org/show_bug.cgi?id=224689 I get the impression that webkit + va gstreamer plugin should work as long as I set the plugin rank. Is this true also for Cog?

Have anyone else got this working? What should the pipeline look like? Does anyone recognize from the screenshot if this is a pixel format issue? 

Version used is 0.14.1 (WPE WebKit 2.38.3), GStreamer 1.20.5 and va gstreamer plugin from 2022-12-19. Running on Yocto Linux (kirkstone) with Wayland (weston) and opengl enabled on Intel x86_64.

![gstreamer_pipeline](https://user-images.githubusercontent.com/93657324/211549902-00f36581-e313-48f7-a676-6f2bcc2ea6a5.png)
![screen](https://user-images.githubusercontent.com/93657324/211551419-d79c64a1-2662-40df-9ef9-03171da3ab59.png)

**Comment by philn** [comment]
Yes the new VA decoders should work in Cog. Can you reproduce this issue with `gst-play-1.0 --videosink glimagesink` ?

**Comment by ceyusa** [comment]
Can you provide the output of `vainfo` ?

**Comment by gustavqmatic** [comment]
This is the vainfo
```
vainfo: VA-API version: 1.15 (libva 2.15.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.4.4 (9ca43202d)
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSliceLP
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSliceLP
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile1            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileVP9Profile3            :	VAEntrypointVLD
      VAProfileHEVCMain422_10         :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         :	VAEntrypointVLD
      VAProfileHEVCMain444_10         :	VAEntrypointEncSliceLP

```
I tested with 
`gst-play-1.0 --videosink glimagesink https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/1080/Big_Buck_Bunny_1080_10s_5MB.mp4`
and it works. It gives the attached pipleline. The pixel format is the same as before, NV12 first and then RGBA, so I guess that is not the issue. But the texture-target and other parameters are different.
![glimagesink](https://user-images.githubusercontent.com/93657324/211786451-f5709bc3-34ab-4966-a4d6-361a05a4cfb3.png)

**Comment by ceyusa** [comment]
Thanks,

But you used the old gstreamer-vaapi plugins using gst-play-1.0. Could you repeat the same exporting export GST_PLUGIN_FEATURE_RANK=vah264dec:MAX,vah265dec:MAX,vampeg2dec:MAX,vavp8dec:MAX,vavp9dec:MAX ??

Also, can you play the same vp8 stream?

Still, the NV12 to RGBA is done in glvideoconvert, while in the browser's pipeline, it's strangely done by glupload.

**Comment by philn** [comment]
Thanks @gustavqmatic can you report this to the GStreamer gitlab?

**Comment by gustavqmatic** [comment]
Sure, I close this and move it to gstreamer instead.

Thank you for the fast help to trouble shot this!
