### ISSUE TITLE
File selector?

### ISSUE THREAD

**Issue by robert-winkler** [Igalia/cog#578]
Hi, cog is a great launcher for webmailing on mobian (on the PinePhone).

However, if I want to send an attachment, I touch the file selector button for uploading the file and nothing happens (downloading attachments works). I tries Posteo and Tutanota.

Any idea how to fix this?

**Comment by philn** [comment]
Cog is not meant to be a desktop web browser, it has very limited support for popups, currently only option menus are supported. If you need a desktop web browser I'd suggest WebKitGTK's Epiphany.

**Comment by robert-winkler** [comment]
Thanks for your comment! Anyway, cog is the best mobian app for webmailing 😉.
