### ISSUE TITLE
Missing tag for 0.18.0

### ISSUE THREAD

**Issue by jameshilliard** [Igalia/cog#601]
I see that the latest [stable release](https://wpewebkit.org/code/) is version [0.18.0](https://wpewebkit.org/releases/cog-0.18.0.tar.xz) however I don't see a corresponding git tag for that version.

**Comment by aperezdc** [comment]
Thanks for the heads up, tag pushed, and while at it I have made the release available here on GitHub as well: https://github.com/Igalia/cog/releases/tag/0.18.0
