### ISSUE TITLE
Provide API documentation for libcogcore

### ISSUE THREAD

**Issue by aperezdc** [Igalia/cog#66]
Most likely the best approach would be to use [GTK-Doc](https://developer.gnome.org/gtk-doc-manual/stable/).

**Comment by Nasah-Kuma** [comment]
The GTK-Doc page isn't found

**Comment by aperezdc** [comment]
The GNOME people have reorganized [developer.gnome.org](https://developer.gnome.org) and I cannot find the GTK-Doc manual anymore there 🤷🏼 

Anyway, we have had documentation since #285 was merged, and it can be read online at [igalia.github.io/cog](https://igalia.github.io/cog/)—I forgot to close this issue earlier.
