### ISSUE TITLE
Ensure that code formatting and style is consistent

### ISSUE THREAD

**Issue by aperezdc** [Igalia/cog#70]
Code style more or less follows that of GLib. It would be good to make sure that all the files are formatted accordingly. For example `platform/cog-platform-fdo.c` has many instances of missing spaces between function names and the opening parenthesis for the argument list.

**Comment by Cwiiis** [comment]
We now have both CI code style checking and a pre-commit hook that checks style - given that a PR to correct all existing mistakes was rejected, is it safe to say that there's nothing left to do here?

**Comment by aperezdc** [comment]
@Cwiiis: you are right, I also think we can close this 👍🏼
