### ISSUE TITLE
Bad rendering of https://ttnmapper.org

### ISSUE THREAD

**Issue by Saviq** [Igalia/cog#719]
Depending on system load, the tiles at https://ttnmapper.org show in the wrong location:

![obraz](https://github.com/Igalia/cog/assets/231077/856fbb89-c53f-4eba-9daa-f64285b6a7b7)

It's easiest to reproduce when zooming in/out, enabling and disabling the different layers

**Comment by gebausim** [comment]
Same issue here on any Leaflet maps. Using newer WPEWebKit with the new Skia backend does fix these for me.

**Comment by gebausim** [comment]
Tried https://ttnmapper.org/ with 2.44.3 and it does appear to be fixed.

**Comment by aperezdc** [comment]
> Tried https://ttnmapper.org/ with 2.44.3 and it does appear to be fixed.

Great, thanks for confirming that this is fixed for you as well. Let's close the issue.
