### ISSUE TITLE
Release pack 0.18.4 for Debian bookworm (stable)

### ISSUE THREAD

**Issue by escherstair** [Igalia/cog#736]
I see that the newest cog pack for the Debian bookworm (stable release at the moment) is [0.16.1-1](https://packages.debian.org/bookworm/cog).
Cog 0.18.4 is available for [sid only](https://packages.debian.org/sid/cog)

I see that @bertogg is the mantainer, so I wonder if it's possible having the pack updated for bookworm.
Thanks in advance.

**Comment by bertogg** [comment]
Hi, Debian stable (bookworm) does not generally install new versions of packages unless there are security vulnerabilities. So there is no plan to have cog 0.18.4 in bookworm.

However you can build it yourself easily:

```
$ apt install libwpewebkit-1.1-dev devscripts curl debhelper libwpebackend-fdo-1.0-dev meson libmanette-0.2-dev libinput-dev libgbm-dev libdrm-dev debian-keyring
$ dget http://deb.debian.org/debian/pool/main/c/cog/cog_0.18.4-1.dsc
$ cd cog-0.18.4/
$ debian/rules binary
```

**Comment by escherstair** [comment]
Hi @bertogg 
your suggestion works perfectly on a bookworm container whith an old release of cog has been already installed.
But if I try with a plain bookworm container, I can't build because of a missing dependency from `libwpewebkit-2.0-dev`.
Even this package is available for Debian sid, but not for bookworm.
Can you share similar instructions to build `libwpewebkit-2.0-dev` for bookworm?

**Comment by bertogg** [comment]
>  Can you share similar instructions to build libwpewebkit-2.0-dev for bookworm?

Hi @escherstair, I shared them last week already, see here: https://github.com/Igalia/cog/issues/737#issuecomment-2393935377
