### ISSUE TITLE
Silently fails to load URIs containing authentication credentials

### ISSUE THREAD

**Issue by philn** [Igalia/cog#75]
Use-case: `cog -P fdo http://foo:password@example.com`
Expected behavior: Page displays
Current behavior: White page

The problem is that in `cog_uri_guess_from_user_input` we use `soup_uri_to_string()` which, as documented, strips the password out.

**Comment by aperezdc** [comment]
Good catch, thanks for the detailed report @philn! I was re-reading the [SoupURI documentation](https://developer.gnome.org/libsoup/2.60/SoupURI.html) and there is no API to reconstruct an URI in full, including the password. Maybe @csaavedra has some other suggestion, but to me it looks like the `SoupURI` API should have a way of reconstructing an URI in full.

Likely we want to report a bug upstream, but in the meantime I suppose we can workaround by manually inserting the password obtained with `soup_uri_get_password()`. WDYT?

**Comment by aperezdc** [comment]
Looking at the code for `cog_uri_guess_from_user_input()` it looks like I will be able to fix this without needing any changes in `libsoup`.
